//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : AppClass.sm
//

#ifndef APPCLASS_SM_H
#define APPCLASS_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class Map1;
class Map1_Start;
class Map1_S0;
class Map1_S1;
class Map1_S2;
class Map1_OK;
class Map1_Error;
class Map1_Default;
class AppClassState;
class AppClassContext;
class AppClass;

class AppClassState :
    public statemap::State
{
public:

    AppClassState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(AppClassContext&) {};
    virtual void Exit(AppClassContext&) {};

    virtual void EOS(AppClassContext& context);
    virtual void Epsilon(AppClassContext& context);
    virtual void Exc_point(AppClassContext& context);
    virtual void Hash(AppClassContext& context);
    virtual void Letter(AppClassContext& context);
    virtual void Math(AppClassContext& context);
    virtual void Number(AppClassContext& context);
    virtual void OpenSymb(AppClassContext& context);
    virtual void Unknown(AppClassContext& context);

protected:

    virtual void Default(AppClassContext& context);
};

class Map1
{
public:

    static Map1_Start Start;
    static Map1_S0 S0;
    static Map1_S1 S1;
    static Map1_S2 S2;
    static Map1_OK OK;
    static Map1_Error Error;
};

class Map1_Default :
    public AppClassState
{
public:

    Map1_Default(const char * const name, const int stateId)
    : AppClassState(name, stateId)
    {};

    virtual void OpenSymb(AppClassContext& context);
    virtual void Exc_point(AppClassContext& context);
    virtual void Letter(AppClassContext& context);
    virtual void Number(AppClassContext& context);
    virtual void Math(AppClassContext& context);
    virtual void Hash(AppClassContext& context);
    virtual void Unknown(AppClassContext& context);
    virtual void EOS(AppClassContext& context);
};

class Map1_Start :
    public Map1_Default
{
public:
    Map1_Start(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void OpenSymb(AppClassContext& context);
};

class Map1_S0 :
    public Map1_Default
{
public:
    Map1_S0(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Exc_point(AppClassContext& context);
    virtual void Letter(AppClassContext& context);
};

class Map1_S1 :
    public Map1_Default
{
public:
    Map1_S1(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Hash(AppClassContext& context);
    virtual void Letter(AppClassContext& context);
    virtual void Math(AppClassContext& context);
    virtual void Number(AppClassContext& context);
};

class Map1_S2 :
    public Map1_Default
{
public:
    Map1_S2(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
};

class Map1_OK :
    public Map1_Default
{
public:
    Map1_OK(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void Epsilon(AppClassContext& context);
};

class Map1_Error :
    public Map1_Default
{
public:
    Map1_Error(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(AppClassContext& context);
    virtual void Epsilon(AppClassContext& context);
};

class AppClassContext :
    public statemap::FSMContext
{
public:

    explicit AppClassContext(AppClass& owner)
    : FSMContext(Map1::Start),
      _owner(owner)
    {};

    AppClassContext(AppClass& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline AppClass& getOwner()
    {
        return (_owner);
    };

    inline AppClassState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<AppClassState&>(*_state);
    };

    inline void EOS()
    {
        setTransition("EOS");
        getState().EOS(*this);
        setTransition(NULL);
    };

    inline void Epsilon()
    {
        setTransition("Epsilon");
        getState().Epsilon(*this);
        setTransition(NULL);
    };

    inline void Exc_point()
    {
        setTransition("Exc_point");
        getState().Exc_point(*this);
        setTransition(NULL);
    };

    inline void Hash()
    {
        setTransition("Hash");
        getState().Hash(*this);
        setTransition(NULL);
    };

    inline void Letter()
    {
        setTransition("Letter");
        getState().Letter(*this);
        setTransition(NULL);
    };

    inline void Math()
    {
        setTransition("Math");
        getState().Math(*this);
        setTransition(NULL);
    };

    inline void Number()
    {
        setTransition("Number");
        getState().Number(*this);
        setTransition(NULL);
    };

    inline void OpenSymb()
    {
        setTransition("OpenSymb");
        getState().OpenSymb(*this);
        setTransition(NULL);
    };

    inline void Unknown()
    {
        setTransition("Unknown");
        getState().Unknown(*this);
        setTransition(NULL);
    };

private:
    AppClass& _owner;
};


#endif // APPCLASS_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
